# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true

# AMQPHub
amqphub:
  amqp10jms:
    pool:
      enabled: true
    remote-url: amqp://localhost:61616
    #username: admin
    #password: admin

# Camel Spring Boot
camel:
  springboot:
    name: large-xml-processor

# Logging
logging:
  config: classpath:logback.xml
  level:
    com.redhat.examples: INFO